import Head from 'next/head'


export default function About() {
    return (
      <div>
        <Head>
          <title>À propos</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
 
  
    <p>à propos... </p>


      
      </div>
    )
  }