import Head from 'next/head'

export default function Event() {
    return (
      <div>
        <Head>
          <title>Évènements</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
     
       <p>Les évènements Les pieds dans l'Eau</p>
      
      </div>
    )
  }